#!/bin/sh
set -e

PROGNAME=$(basename $0)

die() {
    echo "$PROGNAME: $*" >&2
    exit 1
}

usage() {
    if [ "$*" != "" ] ; then
        echo "Error: $*"
    fi

    cat << EOF
Usage: $PROGNAME [OPTION ...] [epi_files]

Options:
    -help       display this usage message and exit
    -ref        name of reference EPI to align to [last file given]
    -trdur      acquisition duration, TR, in seconds [2]
    -pretr n    how many acquisitions to remove [6]
    -totaltr n  total number of acquisitions to keep [120]
    -tfile      full path to time shift file [if not given, standard odd-even]
    -diffmat    do different EPIs have different matrices? [if not given, no]
    -pad_ap n   number of voxels to pad matrices in a/p direction [0]
    -pad_dv n   number of voxels to pad matrices in d/v direction [0]
EOF
    exit 1
}

PRE_TR=0
TOTAL_TR=120
DUR_TR=2
TIME_FILE=false
DIFF_MAT=false
PAD_AP=0
PAD_DV=0
FILENAMES=""

while [ $# -gt 0 ] ; do
    case "$1" in
    -h|--help)
        usage
        ;;
    -ref)
        REF_EPI="$2"
        shift
        ;;
    -trdur)
        DUR_TR="$2"
        shift
        ;;
    -totaltr)
        TOTAL_TR="$2"
        shift
        ;;
    -pretr)
        PRE_TR="$2"
        shift
        ;;
    -tfile)
        TIME_FILE="$2"
        shift
        ;;
    -diffmat)
        DIFF_MAT=true
        ;;
    -pad_ap)
        PAD_AP="$2"
        shift
        ;;
    -pad_dv)
        PAD_DV="$2"
        shift
        ;;
    -*)
        usage "Unknown option '$1'"
        ;;                                                 
    *)  
        FILENAMES=("${FILENAMES[@]}" "$1")
        ;;
    esac
    shift
done

if [[ -z "$FILENAMES" ]] ; then
    usage "Not enough arguments"
fi

#cat <<EOF
#FILENAMES=$FILENAMES
#REF=$REF_EPI
#DUR_TR=$DUR_TR
#TOTAL_TR=$TOTAL_TR
#PRE_TR=$PRE_TR
#TIME_FILE=$TIME_FILE
#DIFF_MAT=$DIFF_MAT
#PAD_AP=$PAD_AP
#PAD_DV=$PAD_DV
#EOF

for FILENAME in "${FILENAMES[@]}" ; do
    echo "'$FILENAME'"
done

