#!/bin/sh
set -e

PROGNAME=$(basename $0)

die() {
    echo "$PROGNAME: $*" >&2
    exit 1
}

usage() {
    if [ "$*" != "" ] ; then
        echo "Error: $*"
    fi

    cat << EOF
Usage: $PROGNAME [OPTION ...] [epi_files]

Options:
    -help       display this usage message and exit
    -ref        name of reference EPI to align to [last file given]
    -trdur      acquisition duration, TR, in seconds [2]
    -pretr n    how many acquisitions to remove [6]
    -totaltr n  total number of acquisitions to keep [120]
    -tfile      full path to time shift file [if not given, standard odd-even]
    -diffmat    do different EPIs have different matrices? [if not given, no]
    -pad_ap n   number of voxels to pad matrices in a/p direction [0]
    -pad_dv n   number of voxels to pad matrices in d/v direction [0]
EOF
    exit 1
}

PRE_TR=0
TOTAL_TR=120
DUR_TR=2
TIME_FILE=false
DIFF_MAT=false
PAD_AP=0
PAD_DV=0
FILENAMES=""

while [ $# -gt 0 ] ; do
    case "$1" in
    -h|--help)
        usage
        ;;
    -ref)
        REF_EPI="$2"
        shift
        ;;
    -trdur)
        DUR_TR="$2"
        shift
        ;;
    -totaltr)
        TOTAL_TR="$2"
        shift
        ;;
    -pretr)
        PRE_TR="$2"
        shift
        ;;
    -tfile)
        TIME_FILE="$2"
        shift
        ;;
    -diffmat)
        DIFF_MAT=true
        ;;
    -pad_ap)
        PAD_AP="$2"
        shift
        ;;
    -pad_dv)
        PAD_DV="$2"
        shift
        ;;
    -*)
        usage "Unknown option '$1'"
        ;;                                                 
    *)  
        FILENAMES=("${FILENAMES[@]}" "$1")
        ;;
    esac
    shift
done

if [[ -z "$FILENAMES" ]] ; then
    usage "Not enough arguments"
fi

rm temp*+orig*

for TEMPFILE in "${FILENAMES[@]}"; do
    if [[ "$TEMPFILE" == *nii.gz ]]; then
        INPUTFILE=${TEMPFILE%.nii.gz}
        SUFFIX='.nii.gz'
    elif [[ "$TEMPFILE" == *nii ]]; then
        INPUTFILE=${TEMPFILE%.nii}
        SUFFIX='.nii'
    elif [[ "$TEMPFILE" == *orig* ]]; then
        INPUTFILE=${TEMPFILE%+*}
        SUFFIX='+orig'
    else
        INPUTFILE=${TEMPFILE}
        SUFFIX='.nii.gz'
    fi
    if [[ -z "${NUM_TR}" ]]; then
        3dTcat -prefix temp+orig ${INPUTFILE}${SUFFIX}'''['${PRE_TR}'..$]'''
    else
        3dTcat -prefix temp+orig ${INPUTFILE}${SUFFIX}'''['${PRE_TR}'..'${NUM_TR}']'''
    fi

    if [ "${TIME_FILE}" == false ]; then
        3dTshift -quintic -prefix temp.ts+orig \
            -TR ${TR}s -tzero 0 -tpattern alt+z \
             temp+orig
    else
        3dTshift -tzero 0 -quintic -prefix temp.ts+orig \
            -TR ${TR}s -tpattern @${TIME_FILE} \
             temp+orig
    fi

    3dWarp -deoblique -prefix temp.ts.do+orig temp.ts+orig 

    if [[ -n "${PAD_AP}" ]]; then 
        3dZeropad -A ${PAD_AP} -P ${PAD_AP} -prefix temp.ts.do.pad+orig temp.ts.do+orig
        rm temp.ts.do+orig*
        3dcopy temp.ts.do.pad+orig temp.ts.do+orig
    fi

    if [ "${DIFF_MAT}" == true ] # if different matrices
    then
        @Align_Centers -base ${REF_EPI} -dset temp.ts.do+orig
        3dresample -master ${REF_EPI} -prefix temp.ts.do.rs+orig -inset temp.ts.do_shft+orig
        3dAFNItoNIFTI -prefix ${INPUTFILE}.ts.do.rs.nii.gz temp.ts.do.rs+orig
    else
        3dAFNItoNIFTI -prefix ${INPUTFILE}.ts.do.nii.gz temp.ts.do+orig
    fi
    rm temp*+orig*
done